#!/usr/bin/env python3
"""
Step 2: pick highlight clips from timestamped transcript and cut video automatically.

Inputs:
- video file path
- transcript result.json (generated by step 1)

Outputs:
- <meta_dir>/clip_plan.json, slice_rules.json
- <clip_dir>/001_06m55s-08m05s_<task>.mp4 ...（runs/clip 全局扁平）
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from slice_logic import (
    DEFAULT_CHUNK_MINUTES,
    DEFAULT_CHUNK_RETRIES,
    DEFAULT_CLIP_HEAD_PAD_MS,
    DEFAULT_CLIP_TAIL_PAD_MS,
    DEFAULT_MAX_SEC,
    DEFAULT_MERGE_NEARBY_GAP_MS,
    DEFAULT_MIN_SEC,
    DEFAULT_RULE_FALLBACK,
    DEFAULT_SLICE_LOGIC,
    SLICE_LOGIC_MODES,
    get_logic_how,
)
from slice_strategy import (
    MODEL_COARSE,
    MODEL_FINE,
    PipelineCancelled,
    SliceRules,
    TIME_RANGE_MODE,
    TIME_RANGE_PARSE_HINT,
    TIME_RANGE_PARSE_HINT_NO_KEY,
    TIME_RANGE_PIPELINE,
    _parse_json_object,
    _parse_time_range_ms,
    build_default_rules,
    check_cancel,
    clips_from_time_range,
    estimate_transcript_stats,
    parse_time_range_with_pad,
    resolve_time_range_with_pad,
    filter_sentences_by_segments,
    format_exclude_block,
    get_sentence_chunks,
    plan_slice_strategy,
    preview_execution_plan,
    resolve_tier,
    retrieve_sentence_ranges,
    sentences_from_ranges,
    should_run_planning_ai,
)

CLIP_DIR_NAME = "clip"
_SEQ_PREFIX_RE = re.compile(r"^(\d{3})_")

# Rough estimate for qwen-plus compatible chat (CNY per 1K tokens). Override via env if needed.
RULE_FALLBACK_MAX_CLIPS = 12
DEFAULT_INPUT_CNY_PER_1K = float(__import__("os").environ.get("CLIP_AI_INPUT_CNY_PER_1K", "0.004"))
DEFAULT_OUTPUT_CNY_PER_1K = float(__import__("os").environ.get("CLIP_AI_OUTPUT_CNY_PER_1K", "0.012"))


def estimate_chat_cost_cny(data: dict[str, Any], prompt_text: str, completion_text: str) -> float:
    usage = data.get("usage") or {}
    prompt_tokens = usage.get("prompt_tokens")
    completion_tokens = usage.get("completion_tokens")
    total_tokens = usage.get("total_tokens")

    if prompt_tokens is None or completion_tokens is None:
        # Fallback heuristic when usage is missing.
        if total_tokens is not None:
            pt = int(float(total_tokens) * 0.75)
            ct = max(0, int(float(total_tokens)) - pt)
        else:
            pt = max(1, int(len(prompt_text) / 1.6))
            ct = max(1, int(len(completion_text) / 1.6))
    else:
        pt = int(float(prompt_tokens))
        ct = int(float(completion_tokens))

    return (pt / 1000.0) * DEFAULT_INPUT_CNY_PER_1K + (ct / 1000.0) * DEFAULT_OUTPUT_CNY_PER_1K


def request_json(
    url: str,
    method: str,
    headers: dict[str, str],
    body: dict[str, Any] | None = None,
    timeout: int = 180,
) -> dict[str, Any]:
    data = None
    if body is not None:
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(url=url, method=method, headers=headers, data=data)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return json.loads(text) if text.strip() else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} {url}\n{detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"请求失败: {url}\n{exc}") from exc


def get_subprocess_window_kwargs() -> dict[str, Any]:
    if sys.platform != "win32":
        return {}
    return {"creationflags": subprocess.CREATE_NO_WINDOW}


def sanitize_name(name: str) -> str:
    cleaned = re.sub(r"[^\w\-\.\u4e00-\u9fff]+", "_", name.strip())
    cleaned = cleaned.strip("._")
    return cleaned or "clip"


def _hms_for_filename(ms: int) -> str:
    """06:55 -> 06m55s（避免 Windows 文件名中的冒号）。"""
    ms = max(0, int(ms))
    total_sec = ms // 1000
    h = total_sec // 3600
    mi = (total_sec % 3600) // 60
    sec = total_sec % 60
    if h > 0:
        return f"{h:02d}h{mi:02d}m{sec:02d}s"
    return f"{mi:02d}m{sec:02d}s"


def _max_clip_seq_in_dir(clip_dir: Path) -> int:
    if not clip_dir.is_dir():
        return 0
    best = 0
    for p in clip_dir.iterdir():
        if not p.is_file() or p.suffix.lower() != ".mp4":
            continue
        m = _SEQ_PREFIX_RE.match(p.name)
        if m:
            best = max(best, int(m.group(1)))
    return best


def _clip_output_basename(seq: int, start_ms: int, end_ms: int, task_slug: str) -> str:
    slug = sanitize_name(task_slug)[:40]
    return f"{seq:03d}_{_hms_for_filename(start_ms)}-{_hms_for_filename(end_ms)}_{slug}.mp4"


def load_glossary_hint(transcript_json: Path) -> str:
    """Rebuild glossary hint from task title/keywords (no glossary.json on disk)."""
    try:
        from transcript_correct import _glossary_hint_block, build_glossary
    except ImportError:
        return ""

    task_dir = transcript_json.parent
    title = task_dir.name
    user_keywords = ""
    manifest = task_dir / "task_manifest.json"
    if manifest.is_file():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            title = str(data.get("task_name") or title)
            user_keywords = str(data.get("user_keywords") or "")
        except Exception:
            pass
    hint = _glossary_hint_block(build_glossary(title, user_keywords))
    if not hint or hint == "（无）":
        return ""
    return "转写实体参考（由标题/关键词自动生成，非预置词表）：\n" + hint


def load_sentences(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise RuntimeError("transcript json 格式错误，期望为句子数组。")
    out: list[dict[str, Any]] = []
    for s in data:
        if not isinstance(s, dict):
            continue
        if "start_ms" not in s or "end_ms" not in s:
            continue
        text = str(s.get("text", "")).strip()
        if not text:
            continue
        out.append(
            {
                "start_ms": int(float(s["start_ms"])),
                "end_ms": int(float(s["end_ms"])),
                "text": text,
            }
        )
    if not out:
        raise RuntimeError("transcript json 中没有可用句子。")
    return out


def build_transcript_for_ai(
    sentences: list[dict[str, Any]], max_lines: int | None = None
) -> str:
    subset = sentences if max_lines is None else sentences[: max(0, max_lines)]
    lines: list[str] = []
    for i, s in enumerate(subset, start=1):
        lines.append(f"{i}|{s['start_ms']}|{s['end_ms']}|{s['text']}")
    return "\n".join(lines)


def _looks_like_legacy_full_custom_prompt(text: str) -> bool:
    """Heuristic: older GUI passed the entire user message as custom_user_prompt."""
    t = text.strip()
    if not t:
        return False
    if "输入格式" in t:
        return True
    if "输出必须是 JSON" in t and "要求:" in t:
        return True
    return False


def duration_constraint_text(min_sec: int, max_sec: int) -> str:
    if max_sec > 0:
        return f"每段时长 {min_sec}-{max_sec} 秒"
    return f"每段至少 {min_sec} 秒，不设最长时长上限（按完整主题/观点切，可到数分钟）"


def build_technical_constraints_block(min_sec: int, max_sec: int) -> str:
    dur = duration_constraint_text(min_sec, max_sec)
    return (
        "【技术约束】（必须遵守）\n"
        f"1) {dur}\n"
        "2) 片段互不重叠\n"
        "3) 段数由转写内容与切片目标决定，不设上限，需要几段就输出几段\n"
        "4) 仅返回一个 JSON 对象，不要 markdown；格式："
        '{"clips":[{"title":"短标题","start_ms":0,"end_ms":0,"reason":"短说明"}]}\n'
        "5) title/reason 各不超过 30 字，勿使用英文双引号\n"
        "6) start_ms/end_ms 必须取自转写行的毫秒时间戳；end_ms 取该主题"
        "**最后一行**的 end_ms，禁止在句子中间截断；多句主题须覆盖完整最后一句\n"
    )


def _strip_markdown_json_fence(text: str) -> str:
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t, flags=re.I)
        t = re.sub(r"\s*```\s*$", "", t)
    return t.strip()


def _extract_balanced_json(text: str, start: int) -> str | None:
    if start < 0 or start >= len(text):
        return None
    open_ch = text[start]
    close_ch = "}" if open_ch == "{" else "]" if open_ch == "[" else ""
    if not close_ch:
        return None
    depth = 0
    in_str = False
    esc = False
    for i in range(start, len(text)):
        ch = text[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
            continue
        if ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _clips_from_parsed_json(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, dict):
        arr = data.get("clips")
        if arr is None:
            for v in data.values():
                if isinstance(v, list):
                    arr = v
                    break
        data = arr
    if not isinstance(data, list):
        raise ValueError("根节点不是 clips 数组。")
    clips: list[dict[str, Any]] = []
    for it in data:
        if not isinstance(it, dict):
            continue
        try:
            start_ms = int(float(it.get("start_ms")))
            end_ms = int(float(it.get("end_ms")))
        except Exception:
            continue
        title = str(it.get("title", "")).strip() or "片段"
        reason = str(it.get("reason", "")).strip()
        if end_ms <= start_ms:
            continue
        clips.append(
            {
                "title": title,
                "start_ms": start_ms,
                "end_ms": end_ms,
                "reason": reason,
            }
        )
    return clips


def _clips_from_loose_regex(content: str) -> list[dict[str, Any]]:
    """Fallback when JSON is broken (e.g. unescaped quotes in reason)."""
    clips: list[dict[str, Any]] = []
    seen: set[tuple[int, int]] = set()
    patterns = [
        re.compile(
            r'"title"\s*:\s*"([^"]{0,80})"\s*,\s*"start_ms"\s*:\s*(\d+)\s*,\s*"end_ms"\s*:\s*(\d+)',
            re.S,
        ),
        re.compile(
            r'"start_ms"\s*:\s*(\d+)\s*,\s*"end_ms"\s*:\s*(\d+)',
            re.S,
        ),
    ]
    for pat in patterns:
        for m in pat.finditer(content):
            if len(m.groups()) == 3:
                title, start_ms, end_ms = m.group(1), int(m.group(2)), int(m.group(3))
            else:
                title, start_ms, end_ms = "片段", int(m.group(1)), int(m.group(2))
            key = (start_ms, end_ms)
            if key in seen or end_ms <= start_ms:
                continue
            seen.add(key)
            clips.append(
                {
                    "title": title.strip() or "片段",
                    "start_ms": start_ms,
                    "end_ms": end_ms,
                    "reason": "",
                }
            )
    return clips


def parse_ai_clips_content(content: str) -> list[dict[str, Any]]:
    text = _strip_markdown_json_fence(content)
    errors: list[str] = []

    for start_ch in ("{", "["):
        pos = text.find(start_ch)
        if pos < 0:
            continue
        chunk = _extract_balanced_json(text, pos)
        if not chunk:
            continue
        try:
            parsed = json.loads(chunk)
            clips = _clips_from_parsed_json(parsed)
            if clips:
                return clips
            errors.append(f"{start_ch} 解析成功但无有效片段")
        except Exception as exc:
            errors.append(f"{start_ch} json.loads: {exc}")

    loose = _clips_from_loose_regex(text)
    if loose:
        return loose

    snippet = text[:240].replace("\n", " ")
    detail = "; ".join(errors[:2]) if errors else "无法识别片段"
    raise ValueError(f"{detail}；响应摘要: {snippet}…")


def build_ai_user_prompt(
    sentences: list[dict[str, Any]],
    min_sec: int,
    max_sec: int,
    slice_goal: str | None,
    slice_logic_how: str | None,
    custom_user_prompt: str | None,
    fine_instruction: str | None = None,
    max_lines: int | None = None,
) -> str:
    transcript_block = build_transcript_for_ai(sentences, max_lines=max_lines)
    tail = "\n\n输入格式: 行号|start_ms|end_ms|text\n" + transcript_block

    cup = (custom_user_prompt or "").strip()
    if cup and _looks_like_legacy_full_custom_prompt(cup):
        prompt = (
            cup.replace("{max_clips}", "0")
            .replace("{min_sec}", str(min_sec))
            .replace("{max_sec}", str(max_sec))
            .replace("{theme}", "")
        )
        if "输入格式" not in prompt:
            prompt = prompt + tail
        else:
            if transcript_block not in prompt and "行号|" not in prompt:
                prompt = prompt + "\n\n" + transcript_block
        return prompt

    parts: list[str] = []
    goal = (slice_goal or "").strip()
    if goal:
        parts.append("【切片目标】（最高优先级，必须满足）\n" + goal)
    logic = (slice_logic_how or "").strip()
    if logic:
        parts.append("【切片逻辑】\n" + logic)
    extra = (fine_instruction or "").strip()
    if extra:
        parts.append("【精切补充】\n" + extra)
    parts.append(build_technical_constraints_block(min_sec, max_sec))
    return "\n\n".join(parts) + tail


def build_ai_user_prompt_with_glossary(
    sentences: list[dict[str, Any]],
    min_sec: int,
    max_sec: int,
    slice_goal: str | None,
    slice_logic_how: str | None,
    custom_user_prompt: str | None,
    transcript_json: Path | None = None,
    fine_instruction: str | None = None,
    max_lines: int | None = None,
) -> str:
    prompt = build_ai_user_prompt(
        sentences=sentences,
        min_sec=min_sec,
        max_sec=max_sec,
        slice_goal=slice_goal,
        slice_logic_how=slice_logic_how,
        custom_user_prompt=custom_user_prompt,
        fine_instruction=fine_instruction,
        max_lines=max_lines,
    )
    if transcript_json is not None:
        hint = load_glossary_hint(transcript_json)
        if hint:
            prompt = prompt + "\n\n" + hint
    return prompt


def split_sentences_by_window(sentences: list[dict[str, Any]], window_ms: int) -> list[list[dict[str, Any]]]:
    if window_ms <= 0:
        return [sentences]
    buckets: dict[int, list[dict[str, Any]]] = {}
    for s in sentences:
        idx = max(0, int(s["start_ms"]) // window_ms)
        buckets.setdefault(idx, []).append(s)
    return [buckets[k] for k in sorted(buckets.keys()) if buckets[k]]


def _chat_completion(
    api_key: str,
    model: str,
    system: str,
    user: str,
    json_object: bool = True,
    cancel_event: Any | None = None,
) -> tuple[str, dict[str, Any], float]:
    check_cancel(cancel_event)
    url = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    body: dict[str, Any] = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.2,
    }
    if json_object:
        body["response_format"] = {"type": "json_object"}
    try:
        data = request_json(url, "POST", headers, body)
    except RuntimeError as exc:
        if not json_object or "response_format" not in str(exc):
            raise
        body.pop("response_format", None)
        data = request_json(url, "POST", headers, body)
    content = (((data.get("choices") or [{}])[0].get("message") or {}).get("content") or "").strip()
    cost = estimate_chat_cost_cny(data, system + user, content)
    return content, data, cost


def _segments_from_parsed(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, dict):
        arr = data.get("segments") or data.get("candidates")
        if arr is None:
            for v in data.values():
                if isinstance(v, list):
                    arr = v
                    break
        data = arr
    if not isinstance(data, list):
        return []
    out: list[dict[str, Any]] = []
    for it in data:
        if not isinstance(it, dict):
            continue
        try:
            s = int(float(it.get("start_ms")))
            e = int(float(it.get("end_ms")))
        except Exception:
            continue
        if e <= s:
            continue
        out.append({"start_ms": s, "end_ms": e, "note": str(it.get("note", "")).strip()})
    return out


def plan_coarse_with_ai(
    api_key: str,
    sentences: list[dict[str, Any]],
    rules: SliceRules,
    slice_goal: str | None,
    model: str | None = None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    check_cancel(cancel_event)
    transcript_block = build_transcript_for_ai(sentences, max_lines=None)
    goal = (slice_goal or "").strip()
    user = (
        f"【粗分任务】\n{rules.coarse_instruction}\n\n"
        f"【切片目标】\n{goal or '（见模式默认）'}\n\n"
        + format_exclude_block(rules.exclude_hints)
        + "输出 JSON："
        '{"segments":[{"start_ms":0,"end_ms":0,"relevance":"high|medium|low","note":"短说明"}]}'
        "。只列与本块目标相关的区间；无则 segments 为空数组。\n\n"
        "输入格式: 行号|start_ms|end_ms|text\n"
        + transcript_block
    )
    system = (
        "你是视频转写粗分助手。只输出合法 JSON，不要 markdown。"
        "segments 的 end_ms 须对齐句尾，勿在句中截断。"
    )
    content, _, cost = _chat_completion(
        api_key,
        model or rules.coarse_model or MODEL_COARSE,
        system,
        user,
        cancel_event=cancel_event,
    )
    if not content:
        return [], cost
    try:
        parsed = _parse_json_object(content)
    except Exception:
        clips = parse_ai_clips_content(content)
        return [{"start_ms": c["start_ms"], "end_ms": c["end_ms"], "note": c.get("reason", "")} for c in clips], cost
    return _segments_from_parsed(parsed), cost


def plan_with_ai(
    api_key: str,
    sentences: list[dict[str, Any]],
    min_sec: int,
    max_sec: int,
    slice_goal: str | None = None,
    slice_logic_how: str | None = None,
    custom_user_prompt: str | None = None,
    transcript_json: Path | None = None,
    fine_instruction: str | None = None,
    exclude_hints: str | None = None,
    model: str | None = None,
    max_lines: int | None = None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    check_cancel(cancel_event)
    prompt = build_ai_user_prompt_with_glossary(
        sentences=sentences,
        min_sec=min_sec,
        max_sec=max_sec,
        slice_goal=slice_goal,
        slice_logic_how=slice_logic_how,
        custom_user_prompt=custom_user_prompt,
        transcript_json=transcript_json,
        fine_instruction=fine_instruction,
        max_lines=max_lines,
    )
    ex = format_exclude_block(exclude_hints or "")
    if ex:
        prompt = ex + "\n" + prompt
    system = (
        "你是视频切片精切助手。只输出一个合法 JSON 对象："
        '{"clips":[{"title":"...","start_ms":0,"end_ms":0,"reason":"..."}]}，'
        "不要 markdown，不要多余说明。段尾须对齐转写句边界，end_ms 取主题最后一句的 end_ms。"
    )
    content, _, cost_cny = _chat_completion(
        api_key,
        model or MODEL_FINE,
        system,
        prompt,
        json_object=True,
        cancel_event=cancel_event,
    )
    if not content:
        raise RuntimeError("AI 未返回可用内容。")
    clips = parse_ai_clips_content(content)
    if not clips:
        raise RuntimeError("AI 未返回有效片段。")
    return clips, cost_cny


def plan_with_ai_in_chunks(
    api_key: str,
    sentences: list[dict[str, Any]],
    rules: SliceRules,
    chunk_retries: int,
    rule_fallback_after_retries: bool,
    slice_goal: str | None = None,
    custom_user_prompt: str | None = None,
    transcript_json: Path | None = None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    chunks = get_sentence_chunks(sentences, rules)
    if not chunks:
        return [], 0.0

    n = len(chunks)
    all_clips: list[dict[str, Any]] = []
    total_cost = 0.0
    for i, ch in enumerate(chunks, start=1):
        check_cancel(cancel_event)
        clips: list[dict[str, Any]] = []
        retries = max(0, chunk_retries)
        success = False
        for attempt in range(1, retries + 2):
            try:
                clips, call_cost = plan_with_ai(
                    api_key=api_key,
                    sentences=ch,
                    min_sec=rules.min_sec,
                    max_sec=rules.max_sec,
                    slice_goal=slice_goal,
                    slice_logic_how=rules.slice_logic_how,
                    custom_user_prompt=custom_user_prompt,
                    transcript_json=transcript_json,
                    fine_instruction=rules.fine_instruction,
                    exclude_hints=rules.exclude_hints,
                    model=rules.fine_model,
                    max_lines=None,
                    cancel_event=cancel_event,
                )
                total_cost += float(call_cost)
                print(f"选段：第 {i}/{n} 段完成，得到 {len(clips)} 个片段")
                success = True
                break
            except Exception as exc:
                print(f"选段：第 {i}/{n} 段失败（第 {attempt} 次）：{exc}")

        if not success:
            if rule_fallback_after_retries:
                print(f"第{i}/{n}块重试后仍失败，规则兜底。")
                clips = plan_with_rules(ch, RULE_FALLBACK_MAX_CLIPS, rules.min_sec, rules.max_sec)
            else:
                clips = []
        all_clips.extend(clips)
    return all_clips, total_cost


def refine_clips_with_ai(
    api_key: str,
    clips: list[dict[str, Any]],
    rules: SliceRules,
    slice_goal: str | None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    check_cancel(cancel_event)
    if len(clips) < 2:
        return clips, 0.0
    lines = [
        f"{i}|{c['start_ms']}|{c['end_ms']}|{c.get('title', '')}|{c.get('reason', '')}"
        for i, c in enumerate(clips, start=1)
    ]
    goal = (slice_goal or "").strip()
    user = (
        "审查下列候选片段：删除不符合切片目标、命中排除条件的；合并相邻且同一主题的段。"
        "合并时不得缩短 end_ms 导致句未说完；仅删除无关段或合并重叠/相邻同主题段。\n"
        + format_exclude_block(rules.exclude_hints)
        + (f"【切片目标】\n{goal}\n\n" if goal else "")
        + f"【精切补充】\n{rules.fine_instruction}\n\n"
        "输入：序号|start_ms|end_ms|title|reason\n"
        + "\n".join(lines)
    )
    system = (
        '只输出 JSON：{"clips":[{"title":"...","start_ms":0,"end_ms":0,"reason":"..."}]}，'
        "不要 markdown。"
    )
    content, _, cost = _chat_completion(
        api_key, rules.fine_model or MODEL_FINE, system, user, cancel_event=cancel_event
    )
    if not content:
        return clips, cost
    try:
        refined = parse_ai_clips_content(content)
        return (refined if refined else clips), cost
    except Exception as exc:
        print(f"精炼轮失败，保留原候选：{exc}")
        return clips, cost


def _run_coarse_map(
    api_key: str,
    sentences: list[dict[str, Any]],
    rules: SliceRules,
    slice_goal: str | None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    chunks = get_sentence_chunks(sentences, rules)
    all_segments: list[dict[str, Any]] = []
    total_cost = 0.0
    for i, ch in enumerate(chunks, start=1):
        check_cancel(cancel_event)
        try:
            segs, cost = plan_coarse_with_ai(
                api_key, ch, rules, slice_goal, cancel_event=cancel_event
            )
            total_cost += cost
            all_segments.extend(segs)
            pass
        except Exception as exc:
            print(f"分析转写第 {i}/{len(chunks)} 段失败：{exc}")
    return all_segments, total_cost


def execute_slice_pipeline(
    api_key: str,
    sentences: list[dict[str, Any]],
    rules: SliceRules,
    slice_goal: str | None,
    transcript_json: Path,
    chunk_retries: int,
    rule_fallback_after_retries: bool,
    custom_user_prompt: str | None = None,
    cancel_event: Any | None = None,
) -> tuple[list[dict[str, Any]], float]:
    check_cancel(cancel_event)
    total_cost = 0.0
    working = list(sentences)

    if rules.base_mode == TIME_RANGE_MODE or rules.pipeline == TIME_RANGE_PIPELINE:
        duration_ms = max((int(s["end_ms"]) for s in sentences), default=0) if sentences else 0
        resolved = resolve_time_range_with_pad(
            slice_goal or "",
            api_key=api_key,
            duration_ms=duration_ms or None,
            request_json_fn=request_json,
        )
        if not resolved:
            hint = TIME_RANGE_PARSE_HINT if (api_key or "").strip().startswith("sk-") else TIME_RANGE_PARSE_HINT_NO_KEY
            raise RuntimeError(f"无法解析时间范围。{hint}")
        s, e, pad, src = resolved
        clips = clips_from_time_range(sentences, s, e, pad_ms=pad)
        tag = "（AI 解析）" if src == "llm" else ""
        print(f"按时间范围{tag}：{s}ms–{e}ms，直裁 {len(clips)} 段（前后各 {pad}ms）")
        return clips, total_cost

    if rules.use_retrieval and rules.search_terms:
        ranges = retrieve_sentence_ranges(sentences, rules.search_terms)
        if ranges:
            working = sentences_from_ranges(sentences, ranges)

    clips: list[dict[str, Any]] = []
    pipeline = rules.pipeline

    if pipeline == "single_pass":
        clips, cost = plan_with_ai(
            api_key=api_key,
            sentences=working,
            min_sec=rules.min_sec,
            max_sec=rules.max_sec,
            slice_goal=slice_goal,
            slice_logic_how=rules.slice_logic_how,
            custom_user_prompt=custom_user_prompt,
            transcript_json=transcript_json,
            fine_instruction=rules.fine_instruction,
            exclude_hints=rules.exclude_hints,
            model=rules.fine_model,
            max_lines=None,
            cancel_event=cancel_event,
        )
        total_cost += cost
    elif pipeline == "chunked_fine":
        clips, cost = plan_with_ai_in_chunks(
            api_key=api_key,
            sentences=working,
            rules=rules,
            chunk_retries=chunk_retries,
            rule_fallback_after_retries=rule_fallback_after_retries,
            slice_goal=slice_goal,
            custom_user_prompt=custom_user_prompt,
            transcript_json=transcript_json,
            cancel_event=cancel_event,
        )
        total_cost += cost
    else:
        coarse_source = working
        segments: list[dict[str, Any]] = []
        if rules.use_coarse_ai:
            segments, coarse_cost = _run_coarse_map(
                api_key, coarse_source, rules, slice_goal, cancel_event=cancel_event
            )
            total_cost += coarse_cost
            if segments:
                refined = filter_sentences_by_segments(working, segments)
                if refined:
                    working = refined

        if not working:
            working = sentences

        clips, fine_cost = plan_with_ai_in_chunks(
            api_key=api_key,
            sentences=working,
            rules=rules,
            chunk_retries=chunk_retries,
            rule_fallback_after_retries=rule_fallback_after_retries,
            slice_goal=slice_goal,
            custom_user_prompt=custom_user_prompt,
            transcript_json=transcript_json,
            cancel_event=cancel_event,
        )
        total_cost += fine_cost

    if rules.use_reduce_pass and clips:
        check_cancel(cancel_event)
        clips, red_cost = refine_clips_with_ai(
            api_key, clips, rules, slice_goal, cancel_event=cancel_event
        )
        total_cost += red_cost

    return clips, total_cost


SENTENCE_END_PUNCT = "。！？!?；;"


def _clip_pad_ms_from_env(name: str, default: int) -> int:
    try:
        return max(0, int(os.environ.get(name, default)))
    except (TypeError, ValueError):
        return default


def get_clip_head_pad_ms() -> int:
    return _clip_pad_ms_from_env("CLIP_HEAD_PAD_MS", DEFAULT_CLIP_HEAD_PAD_MS)


def get_clip_tail_pad_ms() -> int:
    return _clip_pad_ms_from_env("CLIP_TAIL_PAD_MS", DEFAULT_CLIP_TAIL_PAD_MS)


def _ends_with_sentence_punct(text: str) -> bool:
    t = (text or "").rstrip()
    if not t:
        return False
    return t[-1] in SENTENCE_END_PUNCT


def _sentence_indices_overlapping(
    sentences: list[dict[str, Any]], start_ms: int, end_ms: int
) -> list[int]:
    out: list[int] = []
    for i, s in enumerate(sentences):
        sm, em = int(s["start_ms"]), int(s["end_ms"])
        if em > start_ms and sm < end_ms:
            out.append(i)
    return out


def _clip_sentence_span(
    sentences: list[dict[str, Any]], start_ms: int, end_ms: int
) -> tuple[int, int]:
    indices = _sentence_indices_overlapping(sentences, start_ms, end_ms)
    if indices:
        return indices[0], indices[-1]
    if not sentences:
        return 0, 0
    i = 0
    for k, s in enumerate(sentences):
        if int(s["end_ms"]) >= start_ms:
            i = k
            break
    j = len(sentences) - 1
    for k in range(len(sentences) - 1, -1, -1):
        if int(sentences[k]["start_ms"]) <= end_ms:
            j = k
            break
    if i > j:
        j = i
    return i, j


def expand_clips_to_sentences(
    clips: list[dict[str, Any]],
    sentences: list[dict[str, Any]],
    *,
    head_pad_ms: int | None = None,
    tail_pad_ms: int | None = None,
    max_extra_sentences: int = 1,
    video_duration_ms: int | None = None,
) -> list[dict[str, Any]]:
    if not clips or not sentences:
        return clips
    head = get_clip_head_pad_ms() if head_pad_ms is None else max(0, head_pad_ms)
    tail = get_clip_tail_pad_ms() if tail_pad_ms is None else max(0, tail_pad_ms)
    max_extra = max(0, int(max_extra_sentences))
    out: list[dict[str, Any]] = []
    for c in clips:
        start_ms = int(c["start_ms"])
        end_ms = int(c["end_ms"])
        i, j = _clip_sentence_span(sentences, start_ms, end_ms)
        new_start = max(0, int(sentences[i]["start_ms"]) - head)
        new_end = int(sentences[j]["end_ms"]) + tail
        extra_used = 0
        while (
            not _ends_with_sentence_punct(str(sentences[j].get("text", "")))
            and j + 1 < len(sentences)
            and extra_used < max_extra
        ):
            j += 1
            extra_used += 1
            new_end = int(sentences[j]["end_ms"]) + tail
        if video_duration_ms is not None and video_duration_ms > 0:
            new_end = min(new_end, video_duration_ms)
        if new_end <= new_start:
            continue
        expanded = dict(c)
        expanded["start_ms"] = new_start
        expanded["end_ms"] = new_end
        delta = new_end - end_ms
        if delta > 0:
            reason = str(c.get("reason", "")).strip()
            suffix = f"；边界已对齐句尾(+{delta}ms)"
            expanded["reason"] = (reason + suffix) if reason else suffix.lstrip("；")
        out.append(expanded)
    return out


def merge_nearby_clips(
    clips: list[dict[str, Any]], gap_ms: int | None = None
) -> list[dict[str, Any]]:
    if len(clips) < 2:
        return clips
    gap = DEFAULT_MERGE_NEARBY_GAP_MS if gap_ms is None else max(0, gap_ms)
    sorted_clips = sorted(clips, key=lambda x: int(x["start_ms"]))
    merged: list[dict[str, Any]] = [dict(sorted_clips[0])]
    for c in sorted_clips[1:]:
        last = merged[-1]
        gap_actual = int(c["start_ms"]) - int(last["end_ms"])
        if gap_actual <= gap:
            last["end_ms"] = max(int(last["end_ms"]), int(c["end_ms"]))
            t1 = str(last.get("title", "")).strip() or "片段"
            t2 = str(c.get("title", "")).strip()
            if t2 and t2 not in t1:
                last["title"] = f"{t1}+{t2}"[:40]
            r1 = str(last.get("reason", "")).strip()
            r2 = str(c.get("reason", "")).strip()
            if r2:
                last["reason"] = f"{r1}；{r2}" if r1 else r2
        else:
            merged.append(dict(c))
    return merged


def apply_clip_boundary_expansion(
    clips: list[dict[str, Any]],
    sentences: list[dict[str, Any]],
    video_duration_ms: int,
) -> list[dict[str, Any]]:
    if not clips:
        return clips
    before_ends = [int(c["end_ms"]) for c in clips]
    expanded = expand_clips_to_sentences(
        clips, sentences, video_duration_ms=video_duration_ms
    )
    for idx, c in enumerate(expanded):
        if idx < len(before_ends):
            delta = int(c["end_ms"]) - before_ends[idx]
            if delta >= 500:
                print(
                    f"边界扩展：片段 {idx + 1} 尾部 +{delta / 1000:.1f}s（对齐句尾）"
                )
    merged = merge_nearby_clips(expanded)
    if len(merged) != len(clips):
        print(
            f"边界合并：{len(clips)} 段 → {len(merged)} 段（间隙 ≤ {DEFAULT_MERGE_NEARBY_GAP_MS}ms）"
        )
    return merged


def plan_with_rules(sentences: list[dict[str, Any]], max_clips: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    clips: list[dict[str, Any]] = []
    i = 0
    n = len(sentences)
    min_ms = min_sec * 1000
    cap_ms = max_sec * 1000 if max_sec > 0 else 0
    punct = "。！？!?；;"
    while i < n and len(clips) < max_clips:
        start = sentences[i]["start_ms"]
        j = i
        last_good = -1
        while j < n:
            end = sentences[j]["end_ms"]
            dur = end - start
            if dur >= min_ms and sentences[j]["text"].rstrip().endswith(tuple(punct)):
                last_good = j
            if cap_ms > 0 and dur > cap_ms:
                break
            j += 1
        if last_good == -1:
            last_good = min(n - 1, j)
        end = sentences[last_good]["end_ms"]
        if end - start >= min_ms:
            text_sample = "".join(x["text"] for x in sentences[i : last_good + 1])[:18]
            clips.append(
                {
                    "title": f"片段{len(clips)+1}_{text_sample}",
                    "start_ms": start,
                    "end_ms": end,
                    "reason": "规则兜底：按时长和句号边界切分",
                }
            )
        i = last_good + 1
    return clips


def normalize_clips(clips: list[dict[str, Any]], video_duration_ms: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    min_ms = min_sec * 1000
    cap_ms = max_sec * 1000 if max_sec > 0 else 0
    out: list[dict[str, Any]] = []
    for c in clips:
        s = max(0, int(c["start_ms"]))
        e = min(video_duration_ms, int(c["end_ms"]))
        if e <= s:
            continue
        if e - s < min_ms:
            e = min(video_duration_ms, s + min_ms)
        if cap_ms > 0 and e - s > cap_ms:
            e = s + cap_ms
        if e <= s:
            continue
        out.append(
            {
                "title": str(c.get("title", "片段")).strip() or "片段",
                "start_ms": s,
                "end_ms": e,
                "reason": str(c.get("reason", "")).strip(),
            }
        )
    # sort and de-overlap
    out.sort(key=lambda x: x["start_ms"])
    merged: list[dict[str, Any]] = []
    last_end = -1
    for c in out:
        if c["start_ms"] < last_end:
            c["start_ms"] = last_end
            if c["end_ms"] <= c["start_ms"]:
                continue
        merged.append(c)
        last_end = c["end_ms"]
    return merged


def probe_duration_ms(video: Path) -> int:
    cmd = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        str(video),
    ]
    try:
        ret = subprocess.run(cmd, check=True, capture_output=True, text=True, **get_subprocess_window_kwargs())
    except FileNotFoundError:
        raise RuntimeError("未找到 ffprobe，请安装 ffmpeg 并加入 PATH。") from None
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"ffprobe 执行失败: {exc.stderr}") from None
    try:
        sec = float((ret.stdout or "").strip())
        return int(sec * 1000)
    except Exception:
        raise RuntimeError("无法读取视频时长。") from None


def cut_clips(
    video: Path,
    clips: list[dict[str, Any]],
    clip_dir: Path,
    task_slug: str,
    *,
    start_seq: int | None = None,
) -> list[dict[str, Any]]:
    clip_dir.mkdir(parents=True, exist_ok=True)
    sorted_clips = sorted(clips, key=lambda x: int(x["start_ms"]))
    seq = start_seq if start_seq is not None else _max_clip_seq_in_dir(clip_dir) + 1
    outputs: list[dict[str, Any]] = []
    for c in sorted_clips:
        start_ms = int(c["start_ms"])
        end_ms = int(c["end_ms"])
        start_sec = start_ms / 1000.0
        dur_sec = (end_ms - start_ms) / 1000.0
        out_file = clip_dir / _clip_output_basename(seq, start_ms, end_ms, task_slug)
        seq += 1
        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            f"{start_sec:.3f}",
            "-i",
            str(video),
            "-t",
            f"{dur_sec:.3f}",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(out_file),
        ]
        try:
            subprocess.run(cmd, check=True, **get_subprocess_window_kwargs())
        except FileNotFoundError:
            raise RuntimeError("未找到 ffmpeg，请安装并加入 PATH。") from None
        except subprocess.CalledProcessError:
            raise RuntimeError(f"切片失败: {out_file.name}") from None
        outputs.append({**c, "file": str(out_file)})
    return outputs


def run_auto_clip(
    video: Path,
    transcript_json: Path,
    clip_dir: Path,
    meta_dir: Path,
    api_key: str,
    slice_goal: str | None = None,
    slice_logic_how: str | None = None,
    slice_logic_key: str | None = None,
    min_sec: int = DEFAULT_MIN_SEC,
    max_sec: int = DEFAULT_MAX_SEC,
    chunk_minutes: int = DEFAULT_CHUNK_MINUTES,
    chunk_retries: int = DEFAULT_CHUNK_RETRIES,
    rule_fallback_after_retries: bool = DEFAULT_RULE_FALLBACK,
    custom_user_prompt: str | None = None,
    cancel_event: Any | None = None,
    user_keywords: str = "",
    force_tier: str | None = None,
    skip_planning: bool = False,
) -> tuple[list[dict[str, Any]], float]:
    video = video.resolve()
    transcript_json = transcript_json.resolve()
    clip_dir = clip_dir.resolve()
    meta_dir = meta_dir.resolve()
    clip_dir.mkdir(parents=True, exist_ok=True)
    meta_dir.mkdir(parents=True, exist_ok=True)

    if not video.exists():
        raise RuntimeError(f"视频不存在：{video}")
    if not transcript_json.exists():
        raise RuntimeError(f"转写文件不存在：{transcript_json}")
    if min_sec <= 0:
        raise RuntimeError("min_sec 必须大于 0。")
    if max_sec > 0 and min_sec > max_sec:
        raise RuntimeError("max_sec 小于 min_sec，参数非法。")

    sentences = load_sentences(transcript_json)
    duration_ms = probe_duration_ms(video)

    logic_key = (slice_logic_key or DEFAULT_SLICE_LOGIC).strip()
    if logic_key not in SLICE_LOGIC_MODES:
        logic_key = DEFAULT_SLICE_LOGIC
    how = (slice_logic_how or "").strip() or get_logic_how(logic_key)

    stats = estimate_transcript_stats(sentences)
    tier = resolve_tier(stats, force_tier)
    rules = build_default_rules(
        logic_key,
        slice_goal,
        stats,
        tier,
        user_keywords=user_keywords,
        transcript_json=transcript_json,
    )
    rules.min_sec = min_sec
    rules.max_sec = max_sec
    rules.chunk_minutes = chunk_minutes
    rules.slice_logic_how = how
    rules.fine_model = MODEL_FINE
    rules.coarse_model = MODEL_COARSE

    time_range_direct = logic_key == TIME_RANGE_MODE
    goal_text = (slice_goal or "").strip()
    time_range_resolved: tuple[int, int, int, str] | None = None
    if time_range_direct:
        time_range_resolved = resolve_time_range_with_pad(
            goal_text,
            api_key=api_key,
            duration_ms=duration_ms,
            request_json_fn=request_json,
        )
        if not time_range_resolved:
            hint = (
                TIME_RANGE_PARSE_HINT
                if api_key.strip().startswith("sk-")
                else TIME_RANGE_PARSE_HINT_NO_KEY
            )
            raise RuntimeError(f"无法解析时间范围。{hint}")

    will_plan = should_run_planning_ai(
        slice_goal, logic_key, tier, rules, skip_planning=skip_planning
    )

    clips: list[dict[str, Any]] = []
    clip_ai_cost = 0.0

    if time_range_direct and time_range_resolved:
        start_ms, end_ms, pad_ms, src = time_range_resolved
        clips = clips_from_time_range(
            sentences,
            start_ms,
            end_ms,
            pad_ms=pad_ms,
            video_duration_ms=duration_ms,
        )
        tag = "（AI 解析）" if src == "llm" else ""
        print(
            f"按时间范围{tag}：{start_ms}ms–{end_ms}ms，直裁 {len(clips)} 段（前后各 {pad_ms}ms）"
        )
        rules_path = meta_dir / "slice_rules.json"
        rules_path.write_text(
            json.dumps(rules.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8"
        )
    elif api_key.strip():
        key = api_key.strip()
        try:
            if will_plan:
                rules, plan_cost = plan_slice_strategy(
                    key,
                    logic_key,
                    slice_goal,
                    stats,
                    rules,
                    request_json,
                    estimate_chat_cost_cny,
                    sentences=sentences,
                    cancel_event=cancel_event,
                )
                clip_ai_cost += plan_cost

            rules_path = meta_dir / "slice_rules.json"
            rules_path.write_text(
                json.dumps(rules.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8"
            )

            print("正在根据转写选段…")
            clips, pipe_cost = execute_slice_pipeline(
                api_key=key,
                sentences=sentences,
                rules=rules,
                slice_goal=slice_goal,
                transcript_json=transcript_json.resolve(),
                chunk_retries=chunk_retries,
                rule_fallback_after_retries=rule_fallback_after_retries,
                custom_user_prompt=custom_user_prompt,
                cancel_event=cancel_event,
            )
            clip_ai_cost += pipe_cost
            print(
                f"AI 选段完成：共 {len(clips)} 段，估算解析(AI)费用约 {clip_ai_cost:.6f} 元"
            )
        except PipelineCancelled:
            print("切片已取消。")
            raise
    elif time_range_direct:
        hint = (
            TIME_RANGE_PARSE_HINT
            if api_key.strip().startswith("sk-")
            else TIME_RANGE_PARSE_HINT_NO_KEY
        )
        raise RuntimeError(f"无法解析时间范围。{hint}")

    if not clips:
        clips = plan_with_rules(sentences, RULE_FALLBACK_MAX_CLIPS, min_sec, max_sec)
        print(f"AI 未产出有效片段，已改用规则兜底选段：{len(clips)} 段")

    if not time_range_direct:
        clips = apply_clip_boundary_expansion(clips, sentences, video_duration_ms=duration_ms)
        clips = normalize_clips(clips, video_duration_ms=duration_ms, min_sec=min_sec, max_sec=max_sec)
    else:
        clamped: list[dict[str, Any]] = []
        for c in clips:
            s = max(0, int(c["start_ms"]))
            e = min(duration_ms, int(c["end_ms"])) if duration_ms > 0 else int(c["end_ms"])
            if e <= s:
                continue
            item = dict(c)
            item["start_ms"] = s
            item["end_ms"] = e
            clamped.append(item)
        clips = clamped
    if not clips:
        raise RuntimeError("没有可切片段。")

    outputs = cut_clips(video, clips, clip_dir, meta_dir.name)
    plan_file = meta_dir / "clip_plan.json"
    plan_file.write_text(json.dumps(outputs, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"视频：{video}")
    print(f"转写：{transcript_json}")
    print(f"切片输出：{clip_dir}")
    print(f"片段数：{len(outputs)}")
    print(f"规划文件：{plan_file}")
    for o in outputs:
        print(f"- {o['file']}")
    return outputs, float(clip_ai_cost)


def main() -> None:
    parser = argparse.ArgumentParser(description="自动挑片段并切视频（AI优先，规则兜底）。")
    parser.add_argument("--video", type=Path, required=True, help="输入视频")
    parser.add_argument("--transcript-json", type=Path, required=True, help="第一步输出的 result.json")
    parser.add_argument(
        "--clip-dir",
        type=Path,
        default=None,
        help="切片 MP4 输出目录（默认：转写任务上级 runs/clip）",
    )
    parser.add_argument(
        "--meta-dir",
        type=Path,
        default=None,
        help="规划 JSON 输出目录（默认：result.json 所在任务目录）",
    )
    parser.add_argument("--api-key", default="", help="可选：DashScope API Key，提供后启用 AI 选段")
    parser.add_argument("--slice-goal", default="", help="切片目标（自然语言）")
    parser.add_argument("--slice-logic", default=DEFAULT_SLICE_LOGIC, help="切片逻辑模式名")
    parser.add_argument("--min-sec", type=int, default=DEFAULT_MIN_SEC, help="单片段最短秒数")
    parser.add_argument("--max-sec", type=int, default=DEFAULT_MAX_SEC, help="单片段最长秒数，0 表示不设上限")
    parser.add_argument("--chunk-minutes", type=int, default=DEFAULT_CHUNK_MINUTES, help="AI 分段分析窗口（分钟）")
    parser.add_argument("--chunk-retries", type=int, default=DEFAULT_CHUNK_RETRIES, help="每窗口 AI 重试次数")
    parser.add_argument(
        "--rule-fallback-after-retries",
        action="store_true",
        help="AI 重试仍失败时，对该段使用规则兜底（默认关闭）",
    )
    args = parser.parse_args()

    try:
        goal = (args.slice_goal or "").strip() or None
        logic_key = args.slice_logic
        logic_how = get_logic_how(logic_key)
        transcript = args.transcript_json.resolve()
        meta_dir = (args.meta_dir or transcript.parent).resolve()
        clip_dir = (args.clip_dir or meta_dir.parent / CLIP_DIR_NAME).resolve()
        _, clip_cost = run_auto_clip(
            video=args.video,
            transcript_json=transcript,
            clip_dir=clip_dir,
            meta_dir=meta_dir,
            api_key=args.api_key,
            slice_goal=goal,
            slice_logic_how=logic_how,
            slice_logic_key=logic_key,
            min_sec=args.min_sec,
            max_sec=args.max_sec,
            chunk_minutes=args.chunk_minutes,
            chunk_retries=args.chunk_retries,
            rule_fallback_after_retries=args.rule_fallback_after_retries,
        )
        print(f"估算解析(AI)费用合计：¥{clip_cost:.6f}")
    except Exception as exc:
        print(f"错误：{exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
