#!/usr/bin/env python3
"""
Step 2: pick highlight clips from timestamped transcript and cut video automatically.

Inputs:
- video file path
- transcript result.json (generated by step 1)

Outputs:
- <out_dir>/clip_plan.json
- <out_dir>/clips/clip_01_xxx.mp4 ...
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

# Rough estimate for qwen-plus compatible chat (CNY per 1K tokens). Override via env if needed.
DEFAULT_INPUT_CNY_PER_1K = float(__import__("os").environ.get("CLIP_AI_INPUT_CNY_PER_1K", "0.004"))
DEFAULT_OUTPUT_CNY_PER_1K = float(__import__("os").environ.get("CLIP_AI_OUTPUT_CNY_PER_1K", "0.012"))


def estimate_chat_cost_cny(data: dict[str, Any], prompt_text: str, completion_text: str) -> float:
    usage = data.get("usage") or {}
    prompt_tokens = usage.get("prompt_tokens")
    completion_tokens = usage.get("completion_tokens")
    total_tokens = usage.get("total_tokens")

    if prompt_tokens is None or completion_tokens is None:
        # Fallback heuristic when usage is missing.
        if total_tokens is not None:
            pt = int(float(total_tokens) * 0.75)
            ct = max(0, int(float(total_tokens)) - pt)
        else:
            pt = max(1, int(len(prompt_text) / 1.6))
            ct = max(1, int(len(completion_text) / 1.6))
    else:
        pt = int(float(prompt_tokens))
        ct = int(float(completion_tokens))

    return (pt / 1000.0) * DEFAULT_INPUT_CNY_PER_1K + (ct / 1000.0) * DEFAULT_OUTPUT_CNY_PER_1K


def request_json(url: str, method: str, headers: dict[str, str], body: dict[str, Any] | None = None) -> dict[str, Any]:
    data = None
    if body is not None:
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(url=url, method=method, headers=headers, data=data)
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            text = resp.read().decode("utf-8")
            return json.loads(text) if text.strip() else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} {url}\n{detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"请求失败: {url}\n{exc}") from exc


def get_subprocess_window_kwargs() -> dict[str, Any]:
    if sys.platform != "win32":
        return {}
    return {"creationflags": subprocess.CREATE_NO_WINDOW}


def sanitize_name(name: str) -> str:
    cleaned = re.sub(r"[^\w\-\.\u4e00-\u9fff]+", "_", name.strip())
    cleaned = cleaned.strip("._")
    return cleaned or "clip"


def load_sentences(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise RuntimeError("transcript json 格式错误，期望为句子数组。")
    out: list[dict[str, Any]] = []
    for s in data:
        if not isinstance(s, dict):
            continue
        if "start_ms" not in s or "end_ms" not in s:
            continue
        text = str(s.get("text", "")).strip()
        if not text:
            continue
        out.append(
            {
                "start_ms": int(float(s["start_ms"])),
                "end_ms": int(float(s["end_ms"])),
                "text": text,
            }
        )
    if not out:
        raise RuntimeError("transcript json 中没有可用句子。")
    return out


def build_transcript_for_ai(sentences: list[dict[str, Any]], max_lines: int = 300) -> str:
    # Avoid overlong prompt. Keep earliest content for deterministic behavior.
    lines: list[str] = []
    for i, s in enumerate(sentences[:max_lines], start=1):
        lines.append(f"{i}|{s['start_ms']}|{s['end_ms']}|{s['text']}")
    return "\n".join(lines)


def _looks_like_legacy_full_custom_prompt(text: str) -> bool:
    """Heuristic: older GUI passed the entire user message as custom_user_prompt."""
    t = text.strip()
    if not t:
        return False
    if "输入格式" in t:
        return True
    if "输出必须是 JSON" in t and "要求:" in t:
        return True
    return False


def build_fixed_slice_instruction_block(
    max_clips: int,
    min_sec: int,
    max_sec: int,
) -> str:
    """Hard constraints shared by every clip job (偏好仅由「选段策略」说明)。"""
    return (
        "你是短视频剪辑策划助手。给定逐句时间戳文本，请挑选最值得剪成短视频的片段。"
        "输出必须是 JSON，不要 markdown。\n"
        f"要求:\n1) 最多 {max_clips} 段\n2) 每段时长 {min_sec}-{max_sec} 秒\n"
        "3) 不重叠\n4) 仅返回数组，每项字段: title,start_ms,end_ms,reason\n"
    )


def build_ai_user_prompt(
    sentences: list[dict[str, Any]],
    max_clips: int,
    min_sec: int,
    max_sec: int,
    strategy_instructions: str | None,
    custom_user_prompt: str | None,
) -> str:
    """
    Compose the final user message for AI clip planning.

    - Fixed instruction block (JSON shape, duration bounds, etc.) is always included unless
      custom_user_prompt looks like a legacy \"full prompt\" from older clients.
    - strategy_instructions is optional user-editable guidance (persona / priorities).
    """
    transcript_block = build_transcript_for_ai(sentences)
    tail = "\n\n输入格式: 行号|start_ms|end_ms|text\n" + transcript_block

    cup = (custom_user_prompt or "").strip()
    if cup and _looks_like_legacy_full_custom_prompt(cup):
        prompt = (
            cup.replace("{max_clips}", str(max_clips))
            .replace("{min_sec}", str(min_sec))
            .replace("{max_sec}", str(max_sec))
            .replace("{theme}", "")
        )
        if "输入格式" not in prompt:
            prompt = prompt + tail
        else:
            # If user already inlined transcript markers, keep as-is (best effort).
            if transcript_block not in prompt and "行号|" not in prompt:
                prompt = prompt + "\n\n" + transcript_block
        return prompt

    fixed = build_fixed_slice_instruction_block(max_clips, min_sec, max_sec)
    strat = (strategy_instructions or "").strip()
    parts: list[str] = [fixed]
    if strat:
        parts.append("额外选段策略（在固定要求之上执行）：\n" + strat)
    return "\n\n".join(parts) + tail


def split_sentences_by_window(sentences: list[dict[str, Any]], window_ms: int) -> list[list[dict[str, Any]]]:
    if window_ms <= 0:
        return [sentences]
    buckets: dict[int, list[dict[str, Any]]] = {}
    for s in sentences:
        idx = max(0, int(s["start_ms"]) // window_ms)
        buckets.setdefault(idx, []).append(s)
    return [buckets[k] for k in sorted(buckets.keys()) if buckets[k]]


def plan_with_ai(
    api_key: str,
    sentences: list[dict[str, Any]],
    max_clips: int,
    min_sec: int,
    max_sec: int,
    strategy_instructions: str | None = None,
    custom_user_prompt: str | None = None,
) -> tuple[list[dict[str, Any]], float]:
    prompt = build_ai_user_prompt(
        sentences=sentences,
        max_clips=max_clips,
        min_sec=min_sec,
        max_sec=max_sec,
        strategy_instructions=strategy_instructions,
        custom_user_prompt=custom_user_prompt,
    )

    url = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": "qwen-plus",
        "messages": [
            {"role": "system", "content": "你严格按要求返回可解析 JSON。"},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    data = request_json(url, "POST", headers, body)
    content = (
        ((data.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
    ).strip()
    if not content:
        raise RuntimeError("AI 未返回可用内容。")

    cost_cny = estimate_chat_cost_cny(data, prompt, content)

    # Try robust JSON extraction.
    match = re.search(r"\[.*\]", content, flags=re.S)
    json_text = match.group(0) if match else content
    arr = json.loads(json_text)
    if not isinstance(arr, list):
        raise RuntimeError("AI 输出不是数组。")

    clips: list[dict[str, Any]] = []
    for it in arr:
        if not isinstance(it, dict):
            continue
        try:
            start_ms = int(float(it.get("start_ms")))
            end_ms = int(float(it.get("end_ms")))
        except Exception:
            continue
        title = str(it.get("title", "")).strip() or "片段"
        reason = str(it.get("reason", "")).strip()
        if end_ms <= start_ms:
            continue
        clips.append(
            {
                "title": title,
                "start_ms": start_ms,
                "end_ms": end_ms,
                "reason": reason,
            }
        )
    return clips, cost_cny


def plan_with_ai_in_chunks(
    api_key: str,
    sentences: list[dict[str, Any]],
    max_clips: int,
    min_sec: int,
    max_sec: int,
    chunk_minutes: int,
    chunk_retries: int,
    rule_fallback_after_retries: bool,
    strategy_instructions: str | None = None,
    custom_user_prompt: str | None = None,
) -> tuple[list[dict[str, Any]], float]:
    window_ms = max(1, chunk_minutes) * 60 * 1000
    chunks = split_sentences_by_window(sentences, window_ms)
    if not chunks:
        return [], 0.0

    n = len(chunks)
    base = max(1, max_clips // n)
    rem = max(0, max_clips - base * n)

    all_clips: list[dict[str, Any]] = []
    total_cost = 0.0
    for i, ch in enumerate(chunks, start=1):
        quota = base + (1 if i <= rem else 0)
        if quota <= 0:
            continue
        clips: list[dict[str, Any]] = []
        retries = max(0, chunk_retries)
        success = False
        for attempt in range(1, retries + 2):
            try:
                clips, call_cost = plan_with_ai(
                    api_key=api_key,
                    sentences=ch,
                    max_clips=quota,
                    min_sec=min_sec,
                    max_sec=max_sec,
                    strategy_instructions=strategy_instructions,
                    custom_user_prompt=custom_user_prompt,
                )
                total_cost += float(call_cost)
                print(
                    f"AI 分段选段成功：第{i}/{n}段，第{attempt}次，拿到 {len(clips)} 段，"
                    f"本次估算费用约 ¥{call_cost:.6f}"
                )
                success = True
                break
            except Exception as exc:
                print(f"AI 分段选段失败：第{i}/{n}段，第{attempt}次：{exc}")

        if not success:
            if rule_fallback_after_retries:
                print(f"第{i}/{n}段 AI 重试后仍失败，改规则兜底。")
                clips = plan_with_rules(ch, quota, min_sec, max_sec)
            else:
                print(f"第{i}/{n}段 AI 重试后仍失败，跳过该段（未启用规则兜底）。")
                clips = []
        all_clips.extend(clips)
    return all_clips, total_cost


def plan_with_rules(sentences: list[dict[str, Any]], max_clips: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    clips: list[dict[str, Any]] = []
    i = 0
    n = len(sentences)
    min_ms = min_sec * 1000
    max_ms = max_sec * 1000
    punct = "。！？!?；;"
    while i < n and len(clips) < max_clips:
        start = sentences[i]["start_ms"]
        j = i
        last_good = -1
        while j < n:
            end = sentences[j]["end_ms"]
            dur = end - start
            if dur >= min_ms and sentences[j]["text"].rstrip().endswith(tuple(punct)):
                last_good = j
            if dur > max_ms:
                break
            j += 1
        if last_good == -1:
            last_good = min(n - 1, j)
        end = sentences[last_good]["end_ms"]
        if end - start >= min_ms:
            text_sample = "".join(x["text"] for x in sentences[i : last_good + 1])[:18]
            clips.append(
                {
                    "title": f"片段{len(clips)+1}_{text_sample}",
                    "start_ms": start,
                    "end_ms": end,
                    "reason": "规则兜底：按时长和句号边界切分",
                }
            )
        i = last_good + 1
    return clips


def normalize_clips(clips: list[dict[str, Any]], video_duration_ms: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    min_ms = min_sec * 1000
    max_ms = max_sec * 1000
    out: list[dict[str, Any]] = []
    for c in clips:
        s = max(0, int(c["start_ms"]))
        e = min(video_duration_ms, int(c["end_ms"]))
        if e <= s:
            continue
        if e - s < min_ms:
            e = min(video_duration_ms, s + min_ms)
        if e - s > max_ms:
            e = s + max_ms
        if e <= s:
            continue
        out.append(
            {
                "title": str(c.get("title", "片段")).strip() or "片段",
                "start_ms": s,
                "end_ms": e,
                "reason": str(c.get("reason", "")).strip(),
            }
        )
    # sort and de-overlap
    out.sort(key=lambda x: x["start_ms"])
    merged: list[dict[str, Any]] = []
    last_end = -1
    for c in out:
        if c["start_ms"] < last_end:
            c["start_ms"] = last_end
            if c["end_ms"] <= c["start_ms"]:
                continue
        merged.append(c)
        last_end = c["end_ms"]
    return merged


def probe_duration_ms(video: Path) -> int:
    cmd = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        str(video),
    ]
    try:
        ret = subprocess.run(cmd, check=True, capture_output=True, text=True, **get_subprocess_window_kwargs())
    except FileNotFoundError:
        raise RuntimeError("未找到 ffprobe，请安装 ffmpeg 并加入 PATH。") from None
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"ffprobe 执行失败: {exc.stderr}") from None
    try:
        sec = float((ret.stdout or "").strip())
        return int(sec * 1000)
    except Exception:
        raise RuntimeError("无法读取视频时长。") from None


def cut_clips(video: Path, clips: list[dict[str, Any]], out_dir: Path) -> list[dict[str, Any]]:
    clip_dir = out_dir / "clips"
    clip_dir.mkdir(parents=True, exist_ok=True)
    outputs: list[dict[str, Any]] = []
    for idx, c in enumerate(clips, start=1):
        start_sec = c["start_ms"] / 1000.0
        dur_sec = (c["end_ms"] - c["start_ms"]) / 1000.0
        title = sanitize_name(c["title"])
        out_file = clip_dir / f"clip_{idx:02d}_{title}.mp4"
        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            f"{start_sec:.3f}",
            "-i",
            str(video),
            "-t",
            f"{dur_sec:.3f}",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(out_file),
        ]
        try:
            subprocess.run(cmd, check=True, **get_subprocess_window_kwargs())
        except FileNotFoundError:
            raise RuntimeError("未找到 ffmpeg，请安装并加入 PATH。") from None
        except subprocess.CalledProcessError:
            raise RuntimeError(f"切片失败: {out_file.name}") from None
        outputs.append({**c, "file": str(out_file)})
    return outputs


def run_auto_clip(
    video: Path,
    transcript_json: Path,
    out_dir: Path,
    api_key: str,
    max_clips: int,
    min_sec: int,
    max_sec: int,
    chunk_minutes: int,
    chunk_retries: int,
    rule_fallback_after_retries: bool,
    strategy_instructions: str | None = None,
    custom_user_prompt: str | None = None,
) -> tuple[list[dict[str, Any]], float]:
    video = video.resolve()
    transcript_json = transcript_json.resolve()
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not video.exists():
        raise RuntimeError(f"视频不存在：{video}")
    if not transcript_json.exists():
        raise RuntimeError(f"转写文件不存在：{transcript_json}")
    if min_sec <= 0 or max_sec <= 0 or min_sec > max_sec:
        raise RuntimeError("min_sec/max_sec 参数非法。")

    sentences = load_sentences(transcript_json)
    duration_ms = probe_duration_ms(video)

    clips: list[dict[str, Any]] = []
    clip_ai_cost = 0.0
    if api_key.strip():
        clips, clip_ai_cost = plan_with_ai_in_chunks(
            api_key=api_key.strip(),
            sentences=sentences,
            max_clips=max_clips,
            min_sec=min_sec,
            max_sec=max_sec,
            chunk_minutes=chunk_minutes,
            chunk_retries=chunk_retries,
            rule_fallback_after_retries=rule_fallback_after_retries,
            strategy_instructions=strategy_instructions,
            custom_user_prompt=custom_user_prompt,
        )
        print(f"AI 分段选段完成：共 {len(clips)} 段，估算解析(AI)费用约 ¥{clip_ai_cost:.6f}")

    if not clips:
        clips = plan_with_rules(sentences, max_clips, min_sec, max_sec)
        print(f"规则选段：{len(clips)} 段")

    clips = normalize_clips(clips, video_duration_ms=duration_ms, min_sec=min_sec, max_sec=max_sec)
    if not clips:
        raise RuntimeError("没有可切片段。")

    outputs = cut_clips(video, clips, out_dir)
    plan_file = out_dir / "clip_plan.json"
    plan_file.write_text(json.dumps(outputs, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"视频：{video}")
    print(f"转写：{transcript_json}")
    print(f"输出目录：{out_dir}")
    print(f"片段数：{len(outputs)}")
    print(f"规划文件：{plan_file}")
    for o in outputs:
        print(f"- {o['file']}")
    return outputs, float(clip_ai_cost)


def main() -> None:
    parser = argparse.ArgumentParser(description="自动挑片段并切视频（AI优先，规则兜底）。")
    parser.add_argument("--video", type=Path, required=True, help="输入视频")
    parser.add_argument("--transcript-json", type=Path, required=True, help="第一步输出的 result.json")
    parser.add_argument("--out-dir", type=Path, default=Path("clip_output"), help="输出目录")
    parser.add_argument("--api-key", default="", help="可选：DashScope API Key，提供后启用 AI 选段")
    parser.add_argument("--max-clips", type=int, default=6, help="最多生成片段数量")
    parser.add_argument("--min-sec", type=int, default=20, help="单片段最短秒数")
    parser.add_argument("--max-sec", type=int, default=60, help="单片段最长秒数")
    parser.add_argument("--chunk-minutes", type=int, default=30, help="AI 分段分析时长（分钟），默认30")
    parser.add_argument("--chunk-retries", type=int, default=2, help="每段 AI 失败后的重试次数，默认2")
    parser.add_argument(
        "--rule-fallback-after-retries",
        action="store_true",
        help="AI 重试仍失败时，对该段使用规则兜底（默认关闭）",
    )
    args = parser.parse_args()

    try:
        _, clip_cost = run_auto_clip(
            video=args.video,
            transcript_json=args.transcript_json,
            out_dir=args.out_dir,
            api_key=args.api_key,
            max_clips=args.max_clips,
            min_sec=args.min_sec,
            max_sec=args.max_sec,
            chunk_minutes=args.chunk_minutes,
            chunk_retries=args.chunk_retries,
            rule_fallback_after_retries=args.rule_fallback_after_retries,
            strategy_instructions=None,
            custom_user_prompt=None,
        )
        print(f"估算解析(AI)费用合计：¥{clip_cost:.6f}")
    except Exception as exc:
        print(f"错误：{exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
