#!/usr/bin/env python3
"""
Step 2: pick highlight clips from timestamped transcript and cut video automatically.

Inputs:
- video file path
- transcript result.json (generated by step 1)

Outputs:
- <out_dir>/clip_plan.json
- <out_dir>/clips/clip_01_xxx.mp4 ...
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


def request_json(url: str, method: str, headers: dict[str, str], body: dict[str, Any] | None = None) -> dict[str, Any]:
    data = None
    if body is not None:
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(url=url, method=method, headers=headers, data=data)
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            text = resp.read().decode("utf-8")
            return json.loads(text) if text.strip() else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} {url}\n{detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"请求失败: {url}\n{exc}") from exc


def get_subprocess_window_kwargs() -> dict[str, Any]:
    if sys.platform != "win32":
        return {}
    return {"creationflags": subprocess.CREATE_NO_WINDOW}


def sanitize_name(name: str) -> str:
    cleaned = re.sub(r"[^\w\-\.\u4e00-\u9fff]+", "_", name.strip())
    cleaned = cleaned.strip("._")
    return cleaned or "clip"


def load_sentences(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise RuntimeError("transcript json 格式错误，期望为句子数组。")
    out: list[dict[str, Any]] = []
    for s in data:
        if not isinstance(s, dict):
            continue
        if "start_ms" not in s or "end_ms" not in s:
            continue
        text = str(s.get("text", "")).strip()
        if not text:
            continue
        out.append(
            {
                "start_ms": int(float(s["start_ms"])),
                "end_ms": int(float(s["end_ms"])),
                "text": text,
            }
        )
    if not out:
        raise RuntimeError("transcript json 中没有可用句子。")
    return out


def build_transcript_for_ai(sentences: list[dict[str, Any]], max_lines: int = 300) -> str:
    # Avoid overlong prompt. Keep earliest content for deterministic behavior.
    lines: list[str] = []
    for i, s in enumerate(sentences[:max_lines], start=1):
        lines.append(f"{i}|{s['start_ms']}|{s['end_ms']}|{s['text']}")
    return "\n".join(lines)


def split_sentences_by_window(sentences: list[dict[str, Any]], window_ms: int) -> list[list[dict[str, Any]]]:
    if window_ms <= 0:
        return [sentences]
    buckets: dict[int, list[dict[str, Any]]] = {}
    for s in sentences:
        idx = max(0, int(s["start_ms"]) // window_ms)
        buckets.setdefault(idx, []).append(s)
    return [buckets[k] for k in sorted(buckets.keys()) if buckets[k]]


def plan_with_ai(
    api_key: str,
    sentences: list[dict[str, Any]],
    max_clips: int,
    min_sec: int,
    max_sec: int,
    theme: str,
) -> list[dict[str, Any]]:
    transcript_block = build_transcript_for_ai(sentences)
    prompt = (
        "你是短视频剪辑策划助手。给定逐句时间戳文本，请挑选最值得剪成短视频的片段。"
        "输出必须是 JSON，不要 markdown。\n"
        f"要求:\n1) 最多 {max_clips} 段\n2) 每段时长 {min_sec}-{max_sec} 秒\n"
        "3) 不重叠\n4) 仅返回数组，每项字段: title,start_ms,end_ms,reason\n"
        f"5) 主题偏好: {theme}\n\n"
        "输入格式: 行号|start_ms|end_ms|text\n"
        f"{transcript_block}"
    )

    url = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": "qwen-plus",
        "messages": [
            {"role": "system", "content": "你严格按要求返回可解析 JSON。"},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    data = request_json(url, "POST", headers, body)
    content = (
        ((data.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
    ).strip()
    if not content:
        raise RuntimeError("AI 未返回可用内容。")

    # Try robust JSON extraction.
    match = re.search(r"\[.*\]", content, flags=re.S)
    json_text = match.group(0) if match else content
    arr = json.loads(json_text)
    if not isinstance(arr, list):
        raise RuntimeError("AI 输出不是数组。")

    clips: list[dict[str, Any]] = []
    for it in arr:
        if not isinstance(it, dict):
            continue
        try:
            start_ms = int(float(it.get("start_ms")))
            end_ms = int(float(it.get("end_ms")))
        except Exception:
            continue
        title = str(it.get("title", "")).strip() or "片段"
        reason = str(it.get("reason", "")).strip()
        if end_ms <= start_ms:
            continue
        clips.append(
            {
                "title": title,
                "start_ms": start_ms,
                "end_ms": end_ms,
                "reason": reason,
            }
        )
    return clips


def plan_with_ai_in_chunks(
    api_key: str,
    sentences: list[dict[str, Any]],
    max_clips: int,
    min_sec: int,
    max_sec: int,
    theme: str,
    chunk_minutes: int,
    chunk_retries: int,
    rule_fallback_after_retries: bool,
) -> list[dict[str, Any]]:
    window_ms = max(1, chunk_minutes) * 60 * 1000
    chunks = split_sentences_by_window(sentences, window_ms)
    if not chunks:
        return []

    n = len(chunks)
    base = max(1, max_clips // n)
    rem = max(0, max_clips - base * n)

    all_clips: list[dict[str, Any]] = []
    for i, ch in enumerate(chunks, start=1):
        quota = base + (1 if i <= rem else 0)
        if quota <= 0:
            continue
        clips: list[dict[str, Any]] = []
        retries = max(0, chunk_retries)
        success = False
        for attempt in range(1, retries + 2):
            try:
                clips = plan_with_ai(
                    api_key=api_key,
                    sentences=ch,
                    max_clips=quota,
                    min_sec=min_sec,
                    max_sec=max_sec,
                    theme=theme,
                )
                print(f"AI 分段选段成功：第{i}/{n}段，第{attempt}次，拿到 {len(clips)} 段")
                success = True
                break
            except Exception as exc:
                print(f"AI 分段选段失败：第{i}/{n}段，第{attempt}次：{exc}")

        if not success:
            if rule_fallback_after_retries:
                print(f"第{i}/{n}段 AI 重试后仍失败，改规则兜底。")
                clips = plan_with_rules(ch, quota, min_sec, max_sec)
            else:
                print(f"第{i}/{n}段 AI 重试后仍失败，跳过该段（未启用规则兜底）。")
                clips = []
        all_clips.extend(clips)
    return all_clips


def plan_with_rules(sentences: list[dict[str, Any]], max_clips: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    clips: list[dict[str, Any]] = []
    i = 0
    n = len(sentences)
    min_ms = min_sec * 1000
    max_ms = max_sec * 1000
    punct = "。！？!?；;"
    while i < n and len(clips) < max_clips:
        start = sentences[i]["start_ms"]
        j = i
        last_good = -1
        while j < n:
            end = sentences[j]["end_ms"]
            dur = end - start
            if dur >= min_ms and sentences[j]["text"].rstrip().endswith(tuple(punct)):
                last_good = j
            if dur > max_ms:
                break
            j += 1
        if last_good == -1:
            last_good = min(n - 1, j)
        end = sentences[last_good]["end_ms"]
        if end - start >= min_ms:
            text_sample = "".join(x["text"] for x in sentences[i : last_good + 1])[:18]
            clips.append(
                {
                    "title": f"片段{len(clips)+1}_{text_sample}",
                    "start_ms": start,
                    "end_ms": end,
                    "reason": "规则兜底：按时长和句号边界切分",
                }
            )
        i = last_good + 1
    return clips


def normalize_clips(clips: list[dict[str, Any]], video_duration_ms: int, min_sec: int, max_sec: int) -> list[dict[str, Any]]:
    min_ms = min_sec * 1000
    max_ms = max_sec * 1000
    out: list[dict[str, Any]] = []
    for c in clips:
        s = max(0, int(c["start_ms"]))
        e = min(video_duration_ms, int(c["end_ms"]))
        if e <= s:
            continue
        if e - s < min_ms:
            e = min(video_duration_ms, s + min_ms)
        if e - s > max_ms:
            e = s + max_ms
        if e <= s:
            continue
        out.append(
            {
                "title": str(c.get("title", "片段")).strip() or "片段",
                "start_ms": s,
                "end_ms": e,
                "reason": str(c.get("reason", "")).strip(),
            }
        )
    # sort and de-overlap
    out.sort(key=lambda x: x["start_ms"])
    merged: list[dict[str, Any]] = []
    last_end = -1
    for c in out:
        if c["start_ms"] < last_end:
            c["start_ms"] = last_end
            if c["end_ms"] <= c["start_ms"]:
                continue
        merged.append(c)
        last_end = c["end_ms"]
    return merged


def probe_duration_ms(video: Path) -> int:
    cmd = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        str(video),
    ]
    try:
        ret = subprocess.run(cmd, check=True, capture_output=True, text=True, **get_subprocess_window_kwargs())
    except FileNotFoundError:
        raise RuntimeError("未找到 ffprobe，请安装 ffmpeg 并加入 PATH。") from None
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"ffprobe 执行失败: {exc.stderr}") from None
    try:
        sec = float((ret.stdout or "").strip())
        return int(sec * 1000)
    except Exception:
        raise RuntimeError("无法读取视频时长。") from None


def cut_clips(video: Path, clips: list[dict[str, Any]], out_dir: Path) -> list[dict[str, Any]]:
    clip_dir = out_dir / "clips"
    clip_dir.mkdir(parents=True, exist_ok=True)
    outputs: list[dict[str, Any]] = []
    for idx, c in enumerate(clips, start=1):
        start_sec = c["start_ms"] / 1000.0
        dur_sec = (c["end_ms"] - c["start_ms"]) / 1000.0
        title = sanitize_name(c["title"])
        out_file = clip_dir / f"clip_{idx:02d}_{title}.mp4"
        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            f"{start_sec:.3f}",
            "-i",
            str(video),
            "-t",
            f"{dur_sec:.3f}",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(out_file),
        ]
        try:
            subprocess.run(cmd, check=True, **get_subprocess_window_kwargs())
        except FileNotFoundError:
            raise RuntimeError("未找到 ffmpeg，请安装并加入 PATH。") from None
        except subprocess.CalledProcessError:
            raise RuntimeError(f"切片失败: {out_file.name}") from None
        outputs.append({**c, "file": str(out_file)})
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description="自动挑片段并切视频（AI优先，规则兜底）。")
    parser.add_argument("--video", type=Path, required=True, help="输入视频")
    parser.add_argument("--transcript-json", type=Path, required=True, help="第一步输出的 result.json")
    parser.add_argument("--out-dir", type=Path, default=Path("clip_output"), help="输出目录")
    parser.add_argument("--api-key", default="", help="可选：DashScope API Key，提供后启用 AI 选段")
    parser.add_argument("--max-clips", type=int, default=6, help="最多生成片段数量")
    parser.add_argument("--min-sec", type=int, default=20, help="单片段最短秒数")
    parser.add_argument("--max-sec", type=int, default=60, help="单片段最长秒数")
    parser.add_argument("--chunk-minutes", type=int, default=30, help="AI 分段分析时长（分钟），默认30")
    parser.add_argument("--chunk-retries", type=int, default=2, help="每段 AI 失败后的重试次数，默认2")
    parser.add_argument(
        "--rule-fallback-after-retries",
        action="store_true",
        help="AI 重试仍失败时，对该段使用规则兜底（默认关闭）",
    )
    parser.add_argument("--theme", default="冲突、反转、搞笑、高信息密度", help="选段主题偏好")
    args = parser.parse_args()

    video = args.video.resolve()
    transcript = args.transcript_json.resolve()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not video.exists():
        print(f"错误：视频不存在：{video}", file=sys.stderr)
        sys.exit(1)
    if not transcript.exists():
        print(f"错误：transcript 不存在：{transcript}", file=sys.stderr)
        sys.exit(1)
    if args.min_sec <= 0 or args.max_sec <= 0 or args.min_sec > args.max_sec:
        print("错误：min-sec/max-sec 参数非法。", file=sys.stderr)
        sys.exit(1)

    sentences = load_sentences(transcript)
    duration_ms = probe_duration_ms(video)

    clips: list[dict[str, Any]] = []
    if args.api_key.strip():
        try:
            clips = plan_with_ai_in_chunks(
                api_key=args.api_key.strip(),
                sentences=sentences,
                max_clips=args.max_clips,
                min_sec=args.min_sec,
                max_sec=args.max_sec,
                theme=args.theme,
                chunk_minutes=args.chunk_minutes,
                chunk_retries=args.chunk_retries,
                rule_fallback_after_retries=args.rule_fallback_after_retries,
            )
            print(f"AI 分段选段完成：共 {len(clips)} 段")
        except Exception as exc:
            print(f"AI 选段失败，改用规则兜底：{exc}")

    if not clips:
        clips = plan_with_rules(sentences, args.max_clips, args.min_sec, args.max_sec)
        print(f"规则选段：{len(clips)} 段")

    clips = normalize_clips(clips, duration_ms=duration_ms, min_sec=args.min_sec, max_sec=args.max_sec)
    if not clips:
        print("错误：没有可切片段。", file=sys.stderr)
        sys.exit(1)

    outputs = cut_clips(video, clips, out_dir)
    plan_file = out_dir / "clip_plan.json"
    plan_file.write_text(json.dumps(outputs, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"视频：{video}")
    print(f"转写：{transcript}")
    print(f"输出目录：{out_dir}")
    print(f"片段数：{len(outputs)}")
    print(f"规划文件：{plan_file}")
    for o in outputs:
        print(f"- {o['file']}")


if __name__ == "__main__":
    main()
