import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { app, BrowserView, BrowserWindow, ipcMain, session } from "electron";
import type { Session, WebContents } from "electron";

export const DOUYIN_PARTITION = "persist:douyin";

const CHANNEL_CONTINUE = "douyin-login:continue";
const CHANNEL_CANCEL = "douyin-login:cancel";

/** 登录用首页即可同步 Cookie，不必打开视频页（少触发 bytedance:// 调起客户端） */
const DOUYIN_LOGIN_HOME = "https://www.douyin.com";

export function isDouyinUrlLike(u: string): boolean {
  const s = u.toLowerCase();
  return s.includes("douyin.com") || s.includes("iesdouyin.com");
}

export function isDouyinCookieDomain(domain: string): boolean {
  const d = domain.replace(/^\./, "").toLowerCase();
  return d.includes("douyin") || d.includes("iesdouyin");
}

function isBlockedNavigationUrl(url: string): boolean {
  const lower = url.trim().toLowerCase();
  return !lower.startsWith("http://") && !lower.startsWith("https://");
}

/** 拦截 bytedance:// 等，避免 Windows「获取打开此链接的应用」系统弹窗 */
export function attachDouyinProtocolGuards(wc: WebContents): void {
  wc.setWindowOpenHandler(({ url }) => {
    if (isBlockedNavigationUrl(url)) {
      return { action: "deny" };
    }
    void wc.loadURL(url);
    return { action: "deny" };
  });

  const blockIfCustom = (event: { preventDefault: () => void }, url: string) => {
    if (isBlockedNavigationUrl(url)) {
      event.preventDefault();
    }
  };

  wc.on("will-navigate", (event, url) => blockIfCustom(event, url));
  wc.on("will-redirect", (event, url) => blockIfCustom(event, url));
}

function cookieToNetscapeLine(c: import("electron").Cookie): string {
  const domain = c.domain || "";
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const cookiePath = c.path || "/";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expires =
    c.expirationDate && c.expirationDate > 0 ? Math.floor(c.expirationDate) : 0;
  const name = c.name ?? "";
  const value = c.value ?? "";
  return [domain, includeSubdomains, cookiePath, secure, String(expires), name, value].join(
    "\t"
  );
}

export function getDouyinSession(): Session {
  return session.fromPartition(DOUYIN_PARTITION);
}

export async function exportSessionCookiesToFile(
  sess: Session,
  outPath: string
): Promise<{ count: number }> {
  const all = await sess.cookies.get({});
  const filtered = all.filter((c) => c.domain && isDouyinCookieDomain(c.domain));
  const lines = [
    "# Netscape HTTP Cookie File",
    "# https://curl.haxx.se/rfc/cookie_spec.html",
    "# This file was generated by bilibili-to-text (Electron).",
    ...filtered.map(cookieToNetscapeLine),
  ];
  const dir = path.dirname(outPath);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = `${outPath}.tmp`;
  fs.writeFileSync(tmp, `${lines.join("\n")}\n`, "utf-8");
  fs.renameSync(tmp, outPath);
  return { count: filtered.length };
}

function resolveControlsHtmlPath(): string {
  const candidates: string[] = [];
  if (app.isPackaged) {
    candidates.push(
      path.join(process.resourcesPath, "electron", "douyin-login-controls.html")
    );
  }
  const here = path.dirname(fileURLToPath(import.meta.url));
  candidates.push(
    path.join(here, "douyin-login-controls.html"),
    path.join(here, "..", "electron", "douyin-login-controls.html")
  );
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  return candidates[candidates.length - 1]!;
}

const CONTROL_BAR_HEIGHT = 88;

function layoutDouyinViews(
  win: BrowserWindow,
  pageView: BrowserView,
  barView: BrowserView
): void {
  const [w, h] = win.getContentSize();
  const barH = CONTROL_BAR_HEIGHT;
  barView.setBounds({ x: 0, y: h - barH, width: w, height: barH });
  pageView.setBounds({ x: 0, y: 0, width: w, height: Math.max(0, h - barH) });
}

function loadViewWhenReady(view: BrowserView, target: string, isFile: boolean): Promise<void> {
  const wc = view.webContents;
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      cleanup();
      reject(new Error("页面加载超时"));
    }, 90_000);
    const onFail = (_e: Event, code: number, desc: string) => {
      cleanup();
      reject(new Error(`加载失败 (${code}): ${desc}`));
    };
    const onOk = () => {
      cleanup();
      resolve();
    };
    const cleanup = () => {
      clearTimeout(timeout);
      wc.removeListener("did-finish-load", onOk);
      wc.removeListener("did-fail-load", onFail);
    };
    wc.once("did-finish-load", onOk);
    wc.once("did-fail-load", onFail);
    const p = isFile ? wc.loadFile(target) : wc.loadURL(target);
    void p.catch((err) => {
      cleanup();
      reject(err);
    });
  });
}

let activeLoginWindow: BrowserWindow | null = null;

export function closeDouyinLoginUi(): void {
  if (activeLoginWindow && !activeLoginWindow.isDestroyed()) {
    activeLoginWindow.close();
  }
  activeLoginWindow = null;
}

export type DouyinLoginFlowResult =
  | { ok: true; cookieCount: number }
  | { ok: false; canceled: true }
  | { ok: false; error: string };

/**
 * 单窗口：上方抖音页 + 底部操作条。同步 Cookie 后立即关闭，无需保持播放。
 */
export async function openDouyinLoginFlow(opts: {
  repoRoot: string;
  videoUrl?: string;
}): Promise<DouyinLoginFlowResult> {
  void opts.videoUrl;
  if (activeLoginWindow && !activeLoginWindow.isDestroyed()) {
    activeLoginWindow.focus();
    return { ok: false, error: "已有抖音登录窗口打开，请先完成或关闭" };
  }

  const cookiesPath = path.join(opts.repoRoot, "cookies.txt");
  const sess = getDouyinSession();

  return new Promise<DouyinLoginFlowResult>((resolve) => {
    const win = new BrowserWindow({
      width: 960,
      height: 720,
      title: "抖音登录（完成后点底部「继续解析」，窗口会自动关闭）",
      autoHideMenuBar: true,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
      },
    });

    const pageView = new BrowserView({
      webPreferences: {
        partition: DOUYIN_PARTITION,
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    const barView = new BrowserView({
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: false,
      },
    });

    activeLoginWindow = win;
    let settled = false;

    const detachIpc = () => {
      ipcMain.removeListener(CHANNEL_CONTINUE, onContinue);
      ipcMain.removeListener(CHANNEL_CANCEL, onCancel);
    };

    const closeAll = () => {
      detachIpc();
      try {
        if (!win.isDestroyed()) {
          win.removeBrowserView(pageView);
          win.removeBrowserView(barView);
          win.close();
        }
      } catch {
        /* view 可能已销毁 */
      }
      if (activeLoginWindow === win) activeLoginWindow = null;
    };

    const finish = (result: DouyinLoginFlowResult) => {
      if (settled) return;
      settled = true;
      closeAll();
      resolve(result);
    };

    const onCancel = () => {
      finish({ ok: false, canceled: true });
    };

    const onContinue = async () => {
      try {
        const { count } = await exportSessionCookiesToFile(sess, cookiesPath);
        if (count === 0) {
          finish({
            ok: false,
            error: "未检测到抖音 Cookie，请先扫码/登录 douyin.com",
          });
          return;
        }
        finish({ ok: true, cookieCount: count });
      } catch (e) {
        finish({
          ok: false,
          error: e instanceof Error ? e.message : String(e),
        });
      }
    };

    ipcMain.on(CHANNEL_CONTINUE, onContinue);
    ipcMain.on(CHANNEL_CANCEL, onCancel);

    const relayout = () => {
      if (!win.isDestroyed()) {
        layoutDouyinViews(win, pageView, barView);
      }
    };

    win.on("resize", relayout);
    win.on("closed", () => {
      if (!settled) {
        settled = true;
        detachIpc();
        if (activeLoginWindow === win) activeLoginWindow = null;
        resolve({ ok: false, canceled: true });
      }
    });

    win.addBrowserView(pageView);
    win.addBrowserView(barView);
    relayout();

    attachDouyinProtocolGuards(pageView.webContents);

    void (async () => {
      try {
        await loadViewWhenReady(barView, resolveControlsHtmlPath(), true);
        await loadViewWhenReady(pageView, DOUYIN_LOGIN_HOME, false);
        win.show();
        win.focus();
      } catch (e) {
        finish({
          ok: false,
          error: e instanceof Error ? e.message : String(e),
        });
      }
    })();
  });
}

export function countNetscapeCookieEntries(cookiesPath: string): number {
  if (!fs.existsSync(cookiesPath)) return 0;
  let n = 0;
  for (const line of fs.readFileSync(cookiesPath, "utf-8").split(/\r?\n/)) {
    const t = line.trim();
    if (t && !t.startsWith("#") && t.includes("\t")) n += 1;
  }
  return n;
}

export async function getDouyinSessionStatus(repoRoot: string): Promise<{
  hasCookies: boolean;
  entryCount: number;
}> {
  const cookiesPath = path.join(repoRoot, "cookies.txt");
  const fileCount = countNetscapeCookieEntries(cookiesPath);
  let sessionCount = 0;
  try {
    const all = await getDouyinSession().cookies.get({});
    sessionCount = all.filter((c) => c.domain && isDouyinCookieDomain(c.domain)).length;
  } catch {
    /* ignore */
  }
  const entryCount = Math.max(fileCount, sessionCount);
  return { hasCookies: entryCount > 0, entryCount };
}
